### ISSUE TITLE
how to force user account creation in IS?

### ISSUE THREAD

**Issue by yuzaipiaofei** [rhinstaller/initial-setup#74]
I would like to force user to create account in the initial setup, could you help to tell me how to change the IS?

Thanks .

**Comment by M4rtinK** [comment]
You mean even if a user account already exists ? The use creation code in Initial Setup & Anaconda expects a case where no users exist. If there are user accounts already on the system, it can't really handle it as we have no provisions of showing what users exists & resolving if the new user you want to create will collide with a user account that already exists.

**Comment by yuzaipiaofei** [comment]
@M4rtinK 
Thanks for your comment.
I have solved this.
I force the user creation in the IS if the user not existed. then the GIS will not require to create user.
It works now.
